In [1]:
import numpy as np
np.set_printoptions(suppress=True)

In [14]:
p1 = np.load('/rds/project/rds-qxpdOeYWi78/plenoxels/data/real/floss3/poses_bounds.npy')
p1[0]

array([  -0.56796869,    0.74166787,   -0.35684778,   -2.3535273 ,
       4000.        ,    0.80565053,    0.58966777,   -0.05673747,
          2.49801358, 3000.        ,    0.16834128,   -0.31971972,
         -0.93243794,   -1.505387  , 5791.52966728,    6.78811453,
         12.84622196])

In [15]:
p2 = np.load('/rds/project/rds-qxpdOeYWi78/plenoxels/data/real/fern/poses_bounds.npy')
p2[0]

array([   0.02242252,    0.98963074,   -0.141874  ,   -3.67917907,
       3024.        ,    0.99912101,   -0.02720908,   -0.0318884 ,
         -1.60379162, 4032.        ,   -0.035418  ,   -0.14103427,
         -0.98937096,   -0.27680206, 3260.52633288,   17.74708748,
         78.25748707])

In [3]:
p3 = np.load('/rds/project/rds-qxpdOeYWi78/plenoxels/data/real/cup_yellow_circle/poses_bounds.npy')
# p3 = np.load('/rds/project/rds-qxpdOeYWi78/plenoxels/data/real/cup_yellow_circle/hwf_cxcy.npy')
p3[0].shape

(14,)

In [13]:
p3[0]

array([-0.36082542,  0.02712938, -0.93223871, -4.61510539,  0.35683694,
        0.92753396, -0.11112221,  1.58789957,  0.86166839, -0.37275293,
       -0.3443586 ,  2.39182312,  3.97284397,  6.44802153])

In [4]:
pts = np.load('/rds/project/rds-qxpdOeYWi78/plenoxels/data/real/cup_yellow_circle/pts_arr.npy')
view_ids = np.load('/rds/project/rds-qxpdOeYWi78/plenoxels/data/real/cup_yellow_circle/vis_arr.npy')

In [5]:
pts.shape

(74881, 3)

In [6]:
view_ids.shape

(74881, 103)

In [13]:
pts[view_ids[:, 1].astype(bool)].shape

(1998, 3)

In [15]:
np.arange(view_ids.shape[0])

array([    0,     1,     2, ..., 74878, 74879, 74880])